// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArMNP_dRssEoIS45Mffjbzw-oWh-mK5XA',
    appId: '1:751499857535:web:0938f00fe82f54ce4cf94a',
    messagingSenderId: '751499857535',
    projectId: 'tts-tasking-for-smuct',
    authDomain: 'tts-tasking-for-smuct.firebaseapp.com',
    storageBucket: 'tts-tasking-for-smuct.appspot.com',
    measurementId: 'G-WDF86WZX36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA738wD2Inwa8OandPupKoeVYtVfQ0mRzw',
    appId: '1:751499857535:android:f4037e20f86112b54cf94a',
    messagingSenderId: '751499857535',
    projectId: 'tts-tasking-for-smuct',
    storageBucket: 'tts-tasking-for-smuct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpmB8ucWFal1ncO-jpMUXpah5D0K9XLQ',
    appId: '1:751499857535:ios:53223607f77bb5514cf94a',
    messagingSenderId: '751499857535',
    projectId: 'tts-tasking-for-smuct',
    storageBucket: 'tts-tasking-for-smuct.appspot.com',
    iosClientId: '751499857535-1404q69t5jok4rcnl7u51sno4ntffqbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpmB8ucWFal1ncO-jpMUXpah5D0K9XLQ',
    appId: '1:751499857535:ios:53223607f77bb5514cf94a',
    messagingSenderId: '751499857535',
    projectId: 'tts-tasking-for-smuct',
    storageBucket: 'tts-tasking-for-smuct.appspot.com',
    iosClientId: '751499857535-1404q69t5jok4rcnl7u51sno4ntffqbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasking',
  );
}
